default: &default
  adapter: postgresql
  encoding: utf8
  min_messages: WARNING
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] %>
  port: <%= ENV['POSTGRES_PORT'] %>
  pool: 5
  timeout: 5000
  stats_execution_limit: 10


development:
  <<: *default
  database: development

test:
  <<: *default
  database: test