language: python
python:
- 2.7
env:
  matrix:
  - DOCKER_CONTENT_TRUST=0
  global:
  - secure: j3Pso6hSYiph4CCyvN1IRPhA2qMazOlZtdawERfXjO5aAY3ZthjVBtoivoYMbSp1ktimBCvMRZRCyCQNPRz/gIWmbt4fip0tqsGA8+MDRN9vNzmYtH89wSpV6+cHIteUaRv17jetWQk1S6DIfQmWRuMqJrMFe/TLL0xKH7+5OOoU129UkXaUYPUuXZma1xKaxhA/n72olBsX+a3Osnn2EMROAjQHC61SvS3aaQ2JAHMi32i+qK3JWLHlzcersJxqdz1++WdiwfwAQIOuW1sfsKf1Af3fnlGjP1P9KAcEpCBne2yAzppag6lpgcHSTgLtC2A4pMecgXWjNobfrouYooAsQPKMgpWJiLv2mO8tQ4Avj9MaOSLNzoDOQN3Ns14OCdDLizU0J6nZPgejON97cMsRlJipkrPirEYDGXDdJyRYYJleYBe7J7QbNk5CBsEl+9YdoFLL5gmdcfcWw4yq2gisxgvZ9W7n80GO3WEvx+S5ioyf+ZdUUhySIbwdmL8npFDrcQ79DWddooPnPiixWImYKyv1KOWN0isiUOBBD71WGzt3jCg2r07UKgoRE3OQ+uvI9pZ8pAygZwR1KSjo1lRulWyhHz+JwjKZlJGY++pdocZjWSVM87ORrMfnfUJIy0ZiK3ASU6xtla6bhASGiVWL9M4k6Cr5vqgReunw/+4=
  - secure: FXVwpJ2r+2u0CggjdjxS0Szd69Tl8/sT6BTpaviaE/BHJKnpsPm2AItxHzwVfYaY7PbLQdjSGj+gzi5eMCRJLNpEk0CnF3Ajzm8JAKUTsuMNecpuSJhfqqxRZzr8ofIb7SLLaclQPFI3GJeNZYe0aeCmq6IZCaXvadlRIhQZcqEQkjaKzYcBV7Zmju9xp+38lI6XVaL+peMwBNao0HCGwEHYlleKf0uoz5+xQlxF2rJTTyjGOqkH+WmxMKuvV0FR5hqBPU3ttNaaHrl8cQBlVpQ7lpA9Q0WgCoABye3jTNm3g0hSjwgXMOnTj5ELG+NkUtb052dJcTAB82LjVbiFJQg/c/8q9AdQ2nBe93i4s2FjgC3IPOrn+fSQeHu5r7MNphYYUVgFQJXCC+lsLGZK5+19PZeldwlgFg8ewdyOemA4ExZRhf6ddkPBUa7NJgDssyGAaYMwez0GUQxtluqTSn3flU7atbzOBrMetzzGk/VWXVRIXvJaYTH/wlyuU+xNvCVo5kXdXsQHILpJq+Q+/G7GreEYPi1mFbXsKMJmFSPSkEtxHWcI7FxKPVFPLIYljOoST/W2oe5U9xefn6kFNtBvrcFyaWDlwOw9frN1MX6EJvQEYwLQaEkmXGLGIYM2fc2qGOgUMbiKmrb4yXCu7S0q/1g6KB0VHUuIvL5+AfI=
services:
- docker
before_install:
- sudo apt-get update
- docker-compose --version
- pip install docker-compose --upgrade
- docker-compose --version
install:
- cd v01/dockerfiles
- docker-compose -f docker-compose-build.yml build
- docker-compose -f docker-compose-build.yml up -d
- docker-compose ps
before_script:
- pip install requests
- pip install docker
- cd $TRAVIS_BUILD_DIR
script:
- bash ./.travis/linters.sh
- python tests.py